### ISSUE TITLE
PECL extension support.

### ISSUE THREAD

**Issue by Abhinav1217** [phpdocker-io/phpdocker.io#176]
I am new at docker, I am trying to use pecl to install spl_types. I have managed to add php-dev by modifying your dockerfile based on instructions in [stackoverflow](https://stackoverflow.com/questions/3108937/how-to-install-and-run-phpize). But then adding `pecl install spl_types` gives build error on php container. I run `docker system prune` and check all port for availability, before running docker-compose. But still not working. Some guidance please.

**Comment by luispabon** [comment]
If you need to install anything using pecl and phpize I recommend you do it in a single RUN statement, so that you can clean up build dependencies effectively without enlarging your image too much (php-dev adds over 250MB to the container).

Like so:

```
RUN apt update \
   && apt -y install php7.3-dev \
   && pecl install spl_types \
   && apt autoremove --purge php7.3-dev \
   && apt-get clean \
   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
```

I've tried however on php 7.1 to 7.3 and unfortunately they all fail at

```
/tmp/pear/temp/SPL_Types/spl_type.c:74:16: warning: passing argument 1 of 'zval_ptr_dtor' from incompatible pointer type [-Wincompatible-pointer-types]
```

Looks like either dodgy code, incompatible C compiler or more likely incompatible with php 7.x itself. Since [spl_types](https://pecl.php.net/package/SPL_Types) looks abandoned (last release was almost 7 years ago) I would say it's simply not compatible with php 7.x.

**Comment by Abhinav1217** [comment]
It was an old application which I needed to update to php 7. I didn't notice spl_types was abandon. But thanks for the single run statement tip.  Does that works for shell script too. I mean can I put those commands in say in `install_pect.sh` and run ` RUN bash install_pecl.sh` Would that be similar.
