### ISSUE TITLE
nginx.conf fails to mount

### ISSUE THREAD

**Issue by Rarst** [phpdocker-io/phpdocker.io#183]
I have generated a following generic config:

```yaml
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: challenge-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: challenge-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
```

And trying to run `docker-compose up` fails with following errors:

```
challenge-php-fpm is up-to-date
Starting challenge-webserver ... 

[1A[2K
Starting challenge-webserver ... [31merror[0m
[1B
ERROR: for challenge-webserver  Cannot start service webserver: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/c/server/www/challenge/php/phpdocker/nginx/nginx.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/c5d751a4c8dc1f1621aa1d9979ee1d6aeeb99280775015b290910c1671d5c755/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/c5d751a4c8dc1f1621aa1d9979ee1d6aeeb99280775015b290910c1671d5c755/merged/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for webserver  Cannot start service webserver: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/c/server/www/challenge/php/phpdocker/nginx/nginx.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/c5d751a4c8dc1f1621aa1d9979ee1d6aeeb99280775015b290910c1671d5c755/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/c5d751a4c8dc1f1621aa1d9979ee1d6aeeb99280775015b290910c1671d5c755/merged/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Encountered errors while bringing up the project.
```

Windows 7 x64, Docker Toolbox 18.09.3.

**Comment by luispabon** [comment]
Does the nginx file exist? Looks like you only have the docker compose
file.

**Comment by Rarst** [comment]
Yep, definitely exist and in the right place. For a missing file the error is much shorter and more comprehensible (it just says there is no file, no crazy mount stuff).

Might it conflict with image somehow? It seems to have a problem with _this specific destination_. Like it's pretty much doing exactly same thing in `php-fpm` service right next to it and it works without a problem.

**Comment by luispabon** [comment]
Hmmm it could be a weird docker on windows thing regarding mounts into he
virtual machine. I've seen similar on docker for mac. Have you tried
restarting docker, and failing that, resetting it?

**Comment by Rarst** [comment]
Yeah, I had been through full reboot and everything.

If you can't reproduce feel free to close. As I understand Docker doesn't consider Windows 7 very current/supported. I went with something else instead.

**Comment by luispabon** [comment]
To be fair on docker, Windows 7 is neither current nor really supported, I'm amazed it works at all in Windows 7 since Docker requires a fairly recent version of Hyper-V to function.

This is probably a glitch that only happens on your specific set up I'm afraid, otherwise I would've heard more by now! 33% of users of the site come from windows.

**Comment by viorelsfetea** [comment]
OK, so I had the exact same problem and it has nothing to do with Windows 7 (I'm using Windows 10). OP might have found another way of fixing this, but I'm just leaving a note here for posterity.

What it has to do with is that we're using **Docker Toolbox**. OP because he was on Windows 7 and myself, because I am using Windows 10 Home. We both don't have access to Hyper-V so we're using the poor-man's Docker. That works by running Docker in a virtual machine and using that for all its mojo (it installs docker there and runs the commands there using mounted folders). And this here is a simple mounting problem. The folder on the host (where we actually saved the file locally) simply isn't mounted in VirtualBox (in my case, it was mounted incorrectly - another folder was mounted).

**Fix:**
1. First things first, make you sure you have Virtualbox version 6 installed. At the time of this writing, Docker Toolbox was still shipping with VirtualBox 5.2. Upgrading might fix your problem or it may not.

2. Go to VirtualBox, right click on Default (the VM from Docker) > Settings > Shared Folders

3. In my case, I have my project in C:/projects/silly_project_name/. For some strange reason, VirtualBox only mounted C:/Users

4. Add a new entry for the folder containing your project. I did this:
![image](https://user-images.githubusercontent.com/793221/68076303-3a43b580-fdb3-11e9-9795-ee420ce64d6b.png)

5. Update docker-compose.yml just for the webserver part and reference the mounted folder. Please note that I referenced `C:/projects` as `projects`. Meaning, in the virtual machine, the path `/projects` (so the folder `/projects` in the root of the VM) will contain all the files in `C:/projects`. I used the following:
```
    webserver:
      image: nginx:alpine
      container_name: silly_project_name-webserver
      working_dir: /application
      volumes:
          - /projects/silly_project_name/application:/application
          - /projects/silly_project_name/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1025:80"
```

6. Stop everything, eventually remove the containers and start Docker again. I also manually stopped the VM in Virtualbox, but not sure if that is necessary

That's it. Enjoy!
