### ISSUE TITLE
PHP-FPM error log not created automatically

### ISSUE THREAD

**Issue by djozsef** [phpdocker-io/phpdocker.io#223]
The default 'error_log=/var/log/nginx/application_php_errors.log' PHP config directive points to a non-existent file and nor pool manager nor child workers create it upon init. A workaround is to mount a local project file to this default path eg.: 
```        
        - ./var/log/php-error.log:/var/log/nginx/application_php_errors.log
```
Okay, I know it is best to errors from the FPM daemon output but in local development it is much easier to handle separate, scoped log files. At least for me :) 
What do you think? Does it worth dealing with?

BTW have you considered adding a logging container like logio?

**Comment by luispabon** [comment]
Are you getting anything on that file that's not coming out of the container's stdout? Both stdout and sterr internally are redirected to stdout and should appear in your docker logs.

Re logio: I have (not specifically logio) but I haven't found yet a solution that allows such service to actually display docker logs in a way that don't require either apps themselves to publish to the logging service, or some sort of agent to be installed. I keep the generated environments lean and unopinionated for a reason: so that you can take it as a starting point for your deployments.

That said, I accept for sure PRs on the subject. The requirement is that it automatically can access docker logs and don't require either an agent on each container or application config for it to work.

**Comment by djozsef** [comment]
@luispabon I get your point on docker level logging. I was only considering PHP logs, not the full stack. Yes, that would be a complete solution.

Regarding the container stdout/stderr: yes, fpm manager outputs to stdout a part of the PHP error messages emitted by child worker PHP processes. But it is not the full error, may just the first line. The full detail error messages are recorded in `error_log`. This is more verbose and length limited by  `log_errors_max_len` that can be liften in runtime.

Okay by the book we should user FPM manager output and docker STDOUT to gather information but it is not satisfactory when developing in PHP. More information is available via log files since process manager and docker log files are not meant to record the full output. 

I'll put together a config for this and if it fits phpdocker.io I'll PR it.

BTW the volume mount mentioned in the OP is still valid and fixes the logfile issue.

**Comment by luispabon** [comment]
Roger that, I will investigate a way to redirect that error log to the right output. It is possible the first line issue you mention is a buffering setting somewhere on fpm's config as well, afaik default limit is around the 1KB limit.

If you don't have time to make a PR for the other thing, the config itself would be enough for me to crack on it as well :ok_hand:
