### ISSUE TITLE
Mysql on Apple M1 chip Macs

### ISSUE THREAD

**Issue by PhilETaylor** [phpdocker-io/phpdocker.io#310]
When enabling mysql on M1 Macs you get

```
[+] Running 0/1
 ⠙ mysql Pulling                                                           2.0s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

because there is no M1 arm64 specific mysql official image. 

Consider `arm64v8/mysql:oracle` https://hub.docker.com/r/arm64v8/mysql

https://github.com/docker-library/official-images#architectures-other-than-amd64

**Comment by luispabon** [comment]
Apologies I didn't come back to this earlier. Making a special case for mysql would defeat the goal of having as close as possible a runtime environment locally than you would while deployed. Since your message it looks like an arm64 version has been added to the image:

![image](https://user-images.githubusercontent.com/6388823/171993902-77a333a0-015d-4177-8d77-03cca10a1b0b.png)
